name: blog-api

on:
    push:
        branches:
            - master

jobs:
    docker_push:
        runs-on: Ubuntu-24.04

        steps:
            - name: Clean install
              run: |
                npm install
            
            - name: Build Docker image
              run: |
                docker build -t allanbinga/backend-blog:v1.0.0 .

            - name: Log in to DockerHub
              run: |
                echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
            
            - name: Push image to DockerHub
              run: |
                docker push allanbinga/backend-blog:v1.0.0