name: blog-backend-api

on:
  push:
    branches:
      - master

jobs:
  docker_push:
    runs-on: Ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        working-directory: ./backend
        run: |
          docker build -t allanbinga/backend-blog:v1.0.0 .

      - name: Log in to DockerHub
        run: |
          echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

      - name: Push image to DockerHub
        working-directory: ./backend
        run: |
          docker push allanbinga/backend-blog:v1.0.0
